Topics/Models/Topic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Topics.Repository.Models.DB;
using Topics.Services.Implementations;
using Topics.Services.Interfaces;

namespace Topics.Models
{
    public class TopicModel
    {
        private ITopicService topicService;
        public TopicModel()
        {
            this.topicService  = new TopicService();
        }

        public int Id { get; set; }

        public HttpPostedFileBase CoverImg { get; set; }
        
        [Required(ErrorMessage = "A cover image is required"), FileExtensions(ErrorMessage = "Please upload an image file.", Extensions = ".png, .jpg, .jpeg")]
        public string CoverImgName
        {
            get
            {
                if (CoverImg != null)
                    return CoverImg.FileName;
                else
                    return String.Empty;
            }
        }

        public string CoverImgSrc { get; set; }

        public HttpPostedFileBase AvatarImg { get; set; }

        [Required(ErrorMessage = "An avatar image is required"), FileExtensions(ErrorMessage = "Please upload an image file.", Extensions = ".png, .jpg, .jpeg")]
        public string AvatarImgName
        {
            get
            {
                if (CoverImg != null)
                    return CoverImg.FileName;
                else
                    return String.Empty;
            }
        }

        public string AvatarImgSrc { get; set; }



        [Required(ErrorMessage = "Topic name is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Topic title is required")]
        public string Title { get; set; }

        public string Description { get; set; }

        public bool IsMemeber(string username)
        {
            return topicService.IsMember(this, username);
        }
        public List<PostModel> Posts { get; set; }

        public string Owner { get; set; }
        public List<string> Moderators { get; set; }

    }
}

Topics/Controllers/TopicController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Topics.Auth;
using Topics.Models;
using Topics.Services.Interfaces;

namespace Topics.Controllers
{
    [@Authorize(Roles = "basic")]
    public class TopicController : Controller
    {
        private readonly ITopicService topicService;
        private readonly IPostService postService;

        public TopicController(ITopicService topicService, IPostService postService)
        {
            this.topicService = topicService;
            this.postService = postService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            List<TopicModel> topics = topicService.GetTopics();
            ViewBag.Topics = topics;
            return View();
        }

        [HttpGet]
        public ActionResult Get(string id)
        {
            TopicModel topic = topicService.GetTopic(id);
            Principal user = (Principal)HttpContext.User;

            bool isMember = topicService.IsMember(topic, user.Username);
            ViewBag.IsMember = isMember;
            ViewBag.TopicName = id;


            ISet<string> upVotedPosts = postService.GetVotedPosts(user.Username, true);
            ViewBag.UpVotedPosts = upVotedPosts;

            ISet<string> downVotedPosts = postService.GetVotedPosts(user.Username, false);
            ViewBag.DownVotedPosts = downVotedPosts;

            topic.Posts = postService.GetTopicPosts(id);
            return View(topic);
        }

        [HttpPost]
        public ActionResult Create(ModalTopicModel model)
        {
            if (!ModelState.IsValid)
                return Redirect("/");

            Principal user = (Principal)HttpContext.User;

            topicService.CreateTopic(model.Topic, user.Username);
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpPost]
        public ActionResult Edit(ModalTopicModel model)
        {
            System.Diagnostics.Debug.WriteLine(model.Id);

            if (!ModelState.IsValid)
                return Redirect("/");

            Principal user = (Principal)HttpContext.User;

            topicService.EditTopic(model.Topic, user.Username);
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpGet]
        public ActionResult Join(string id)
        {
            Principal user = (Principal)HttpContext.User;
            TopicModel topic = topicService.GetTopic(id);

            topicService.AddMember(topic, user.Username);
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpGet]
        public ActionResult Leave(string id)
        {
            Principal user = (Principal)HttpContext.User;
            TopicModel topic = topicService.GetTopic(id);

            topicService.DeleteMember(topic, user.Username);
            return Redirect(Request.UrlReferrer.ToString());
        }
        
        [HttpPost]
        public ActionResult AddModerator(TopicModeratorModel mod) 
        {
            if (!ModelState.IsValid)
                return Redirect(Request.UrlReferrer.ToString());

            TopicModel topic = topicService.GetTopic(mod.TopicName);
            Principal user = (Principal)HttpContext.User;

            if (!topic.Owner.Equals(user.Username))
                return Redirect(Request.UrlReferrer.ToString());

            topicService.AddModerator(mod.ModUsername, mod.TopicName);
            return Redirect(Request.UrlReferrer.ToString());
        }

        public ActionResult RemoveModerator(string username, string topicName)
        {
            
            TopicModel topic = topicService.GetTopic(topicName);
            Principal user = (Principal)HttpContext.User;

            if (!topic.Owner.Equals(user.Username))
                return Redirect(Request.UrlReferrer.ToString());

            topicService.RemoveModerator(username, topicName);

            return Redirect(Request.UrlReferrer.ToString());
        }
    }

}

Topics/Views/Topic/Get.cshtml
@using Topics.Auth;
@using Topics.Models;
@{
    ViewBag.Title = "GetTopic";
    Layout = "~/Views/Shared/Layouts/MainLayout.cshtml";
    Principal user = (Principal)HttpContext.Current.User;
    bool isOwner = user.Username.Equals(Model.Owner);
    bool isMod = Model.Moderators.Contains(user.Username);
}
@model Topics.Models.TopicModel

@if (Model == null)
{
    <h1>404: Topic not found</h1>
} else
{

<div class="container">
    <div class="p-1 mb-4 d-flex flex-column">

        @if (string.IsNullOrEmpty(Model.CoverImgSrc))
        {
            <div class="rounded bg-dark cover"></div>
        }
        else
        {
            <img src="@Model.CoverImgSrc" class="cover" alt="Cover image" />
        }
        
        <div class="d-flex align-items-md-center justify-content-md-between px-5 py-2 gap-3 flex-column border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 w-75 align-self-center translate-middle-y bg-light">
            <div class="d-flex align-items-center gap-2 justify-content-center">
                @if (string.IsNullOrEmpty(Model.AvatarImgSrc))
                {
                    <img src="https://st2.depositphotos.com/1309454/5538/v/950/depositphotos_55380965-stock-illustration-avatars-characters.jpg" alt="avatar image" class="avatar shadow-sm border" />
                }
                else
                {
                    <img src="@Model.AvatarImgSrc" alt="avatar image" class="avatar shadow-sm border" />
                }
                <h1>@Model.Name</h1>
            </div>
            <div class="btn-group btn-group-lg">

                @if (isMod)
                {
                    <button class="btn btn-lg btn-warning" data-bs-toggle="modal" data-bs-target="#modal-edit-topic">Edit</button>
                }
                else if (isOwner)
                {
                    <button class="btn btn-lg btn-warning" data-bs-toggle="modal" data-bs-target="#modal-edit-topic">Edit</button>
                    @Html.ActionLink("Delete", "Delete/" + Model.Name, "Topic", null, new { @class = "btn btn-lg btn-danger" })
                }
                else if (ViewBag.IsMember)
                {
                    @Html.ActionLink("Leave", "Leave/" + Model.Name, "Topic", null, new { @class = "btn btn-lg btn-danger" })
                }
                else
                {
                    @Html.ActionLink("Join", "Join/" + Model.Name, "Topic", null, new { @class = "btn btn-lg btn-primary" })
                }
            </div>
        </div>
    </div>
    @if (isOwner || isMod)
    {
        @Html.Partial("~/Views/Shared/ModalTopic.cshtml", new ModalTopicModel() { Id = "edit-topic", Topic = Model, Label = "Edit Topic", Action = ActionType.Edit })
        @Html.Partial("~/Views/Shared/ModalAddModarator.cshtml", new TopicModeratorModel() { Mods = Model.Moderators, TopicName = Model.Name })
    }

    <div class="row g-5">
        <div class="col-md-8">
            @Html.Partial("~/Views/Shared/Posts.cshtml", new PostList() { Posts = Model.Posts })
        </div>

        <div class="col-md-4">
            <div class="position-sticky" style="top: 2rem;">
                <div class="p-4 mb-3 bg-light rounded">
                    <h4 class="fst-italic">About</h4>
                    <p class="mb-0">@Model.Description</p>
                </div>

                <div class="p-4">
                    <h4 class="fst-italic">Owner</h4>
                    <ol class="list-unstyled mb-0">
                        <li><a href="#" class="link-primary text-decoration-none">@@@Model.Owner</a></li>
                    </ol>
                </div>

                <div class="p-4">
                    <div class="d-flex gap-1 align-items-center">
                        <h4 class="fst-italic">Moderatos</h4>
                        @if (isOwner)
                        {
                            <button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modal-add-moderator">Edit</button>
                        }
                    </div>
                    <ol class="list-group my-2">
                        @foreach (string mod in Model.Moderators)
                        {
                            <li class="list-group-item">
                                <a href="#" class="link-primary text-decoration-none">@@@mod</a>
                            </li>
                        }
                    </ol>
                </div>
            </div>
        </div>
    </div>

</div>
}

Topics/Views/Topic/Index.cshtml
@using Topics.Auth;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layouts/MainLayout.cshtml";
    Principal user = (Principal)HttpContext.Current.User;
}

@using Topics.Models

<div class="container d-flex flex-column align-items-stretch gap-4 my-4" id="observer-root">
    @foreach (TopicModel topic in ViewBag.Topics)
    {
        <div class="col card shadow-sm">
            <img name="observer-item" data-src="@topic.CoverImgSrc" class="bd-placeholder-img card-img-top object-fit-cover" alt="Cover image" height="225" width="100%" />
            <div class="card-body d-flex align-items-md-center justify-content-md-between px-5 py-2 gap-3 flex-column  overflow-hidden flex-md-row h-md-250 w-75 align-self-center">
                <div class="d-flex align-items-center gap-2 justify-content-center">
                    @if (string.IsNullOrEmpty(topic.AvatarImgSrc))
                    {
                        <img name="observer-item" data-src="https://st2.depositphotos.com/1309454/5538/v/950/depositphotos_55380965-stock-illustration-avatars-characters.jpg" alt="avatar image" class="avatar shadow-sm border" />
                    }
                    else
                    {
                        <img name="observer-item" data-src="@topic.AvatarImgSrc" alt="avatar image" class="avatar shadow-sm border" />
                    }
                    <div class="d-flex flex-column justify-content-center">
                        <span class="text-black">@topic.Title</span>
                        <span class="text-secondary">@@@topic.Name</span>
                    </div>
                </div>
                <div class="btn-group">
                    @if (topic.IsMemeber(user.Username))
                    {
                        @Html.ActionLink("Leave", "Leave/" + topic.Name, "Topic", null, new { @class = "btn btn-danger" })
                    }
                    else
                    {
                        @Html.ActionLink("Join", "Join/" + topic.Name, "Topic", null, new { @class = "btn btn-primary" })
                    }
                    @Html.ActionLink("View", "Get/" + topic.Name, "Topic", null, new { @class = "btn btn-outline-secondary" })
                </div>
            </div>
        </div>
    }
</div>

<script>
    const divRoot = document.getElementById("observer-root");

    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (!entry.isIntersecting) return;

            const element = entry.target;
            const src = element.getAttribute("data-src");

            element.setAttribute("src", src);
            element.removeAttribute("data-src");

            observer.unobserve(element);
        });
    }, {
        root: divRoot.target,
        rootMargin: "0px",
        threshold: 0.25
    });

    const divItems = document.getElementsByName("observer-item");
    divItems.forEach(item => observer.observe(item));

 </script>